// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbg0X47dCi-tOAP7Pd2z-es11L-sNOky8',
    appId: '1:332948272800:web:ec6ce1879b28d4cda33bc5',
    messagingSenderId: '332948272800',
    projectId: 'spaceexplore-e7f19',
    authDomain: 'spaceexplore-e7f19.firebaseapp.com',
    storageBucket: 'spaceexplore-e7f19.firebasestorage.app',
    measurementId: 'G-SW7X11HVXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAvul2TJuQc-1bt-o3y1PVxG6Vv5w2A9k',
    appId: '1:332948272800:android:aef19c8f486946caa33bc5',
    messagingSenderId: '332948272800',
    projectId: 'spaceexplore-e7f19',
    storageBucket: 'spaceexplore-e7f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKV3ZUpAWq9EZR5HNW1N8vqve5VOreb8',
    appId: '1:332948272800:ios:eaf59e8d7d8b0a88a33bc5',
    messagingSenderId: '332948272800',
    projectId: 'spaceexplore-e7f19',
    storageBucket: 'spaceexplore-e7f19.firebasestorage.app',
    iosBundleId: 'com.apod.apod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbg0X47dCi-tOAP7Pd2z-es11L-sNOky8',
    appId: '1:332948272800:web:fc387e342fccca21a33bc5',
    messagingSenderId: '332948272800',
    projectId: 'spaceexplore-e7f19',
    authDomain: 'spaceexplore-e7f19.firebaseapp.com',
    storageBucket: 'spaceexplore-e7f19.firebasestorage.app',
    measurementId: 'G-1L7JE7MHHS',
  );
}
